In [1]:
from tensorflow.keras.preprocessing.text  import one_hot


In [4]:
# Define the sentences
sentences = [
    "The cat sat on the mat.",
    "I love to play soccer.",
    "The weather is sunny today.",
    "She enjoys reading books.",
    "He is learning to code in Python.",
    "The dog barked at the mailman.",
    "They went hiking in the mountains.",
    "Cooking is my favorite hobby.",
    "Music brings joy to my life.",
    "Traveling opens up new experiences.",
    "football is easy to learn",
    "football is easeist to play"
]


In [6]:
sentences
voc_size=10000



In [7]:
## define the vocalbary size
one_hot_repr =[one_hot(words,voc_size) for words in sentences]


In [8]:
one_hot_repr

[[339, 572, 275, 88, 339, 156],
 [69, 474, 35, 281, 849],
 [339, 946, 70, 852, 375],
 [908, 219, 731, 177],
 [409, 70, 606, 35, 867, 317, 819],
 [339, 530, 653, 38, 339, 162],
 [834, 36, 646, 317, 339, 510],
 [199, 70, 82, 825, 737],
 [927, 231, 860, 35, 82, 987],
 [346, 93, 947, 207, 71],
 [582, 70, 181, 35, 905],
 [582, 70, 671, 35, 281]]

In [9]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [10]:
import numpy

In [11]:
sent_length = 8
embedded_docs =pad_sequences(one_hot_repr,padding= 'pre',maxlen=sent_length)

In [12]:
embedded_docs

array([[  0,   0, 339, 572, 275,  88, 339, 156],
       [  0,   0,   0,  69, 474,  35, 281, 849],
       [  0,   0,   0, 339, 946,  70, 852, 375],
       [  0,   0,   0,   0, 908, 219, 731, 177],
       [  0, 409,  70, 606,  35, 867, 317, 819],
       [  0,   0, 339, 530, 653,  38, 339, 162],
       [  0,   0, 834,  36, 646, 317, 339, 510],
       [  0,   0,   0, 199,  70,  82, 825, 737],
       [  0,   0, 927, 231, 860,  35,  82, 987],
       [  0,   0,   0, 346,  93, 947, 207,  71],
       [  0,   0,   0, 582,  70, 181,  35, 905],
       [  0,   0,   0, 582,  70, 671,  35, 281]])

In [14]:
## feature represntation 
## i need 10 feautures 
dim =10


In [15]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length =sent_length))

In [16]:
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             10000     
                                                                 
Total params: 10000 (39.06 KB)
Trainable params: 10000 (39.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 903ms/step


array([[[-1.51524171e-02,  1.53872110e-02, -2.20226999e-02,
         -7.03905895e-03, -4.94087823e-02, -2.59167198e-02,
          4.82926033e-02, -4.80366461e-02, -4.89665531e-02,
          2.25897878e-03],
        [-1.51524171e-02,  1.53872110e-02, -2.20226999e-02,
         -7.03905895e-03, -4.94087823e-02, -2.59167198e-02,
          4.82926033e-02, -4.80366461e-02, -4.89665531e-02,
          2.25897878e-03],
        [ 4.52003814e-02, -3.10888048e-02,  4.58931960e-02,
         -1.45080462e-02, -2.78944261e-02, -2.77049430e-02,
          2.13919021e-02,  2.47637369e-02,  3.35504077e-02,
         -2.90107727e-03],
        [ 3.11666243e-02, -4.64838743e-03,  4.71796133e-02,
          5.05186245e-03, -3.91534679e-02,  4.66415994e-02,
          1.52827613e-02, -4.90873568e-02, -2.89290193e-02,
          5.99992275e-03],
        [-4.55468893e-03, -2.59081125e-02, -2.18541268e-02,
          2.33817212e-02,  4.81192023e-03, -2.86037810e-02,
         -2.55649090e-02,  1.67509951e-02,  1.261908

In [21]:
sentences[0]

'The cat sat on the mat.'

In [22]:
embedded_docs[0]

array([  0,   0, 339, 572, 275,  88, 339, 156])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 115ms/step


array([[-0.01515242,  0.01538721, -0.0220227 , -0.00703906, -0.04940878,
        -0.02591672,  0.0482926 , -0.04803665, -0.04896655,  0.00225898],
       [-0.01515242,  0.01538721, -0.0220227 , -0.00703906, -0.04940878,
        -0.02591672,  0.0482926 , -0.04803665, -0.04896655,  0.00225898],
       [ 0.04520038, -0.0310888 ,  0.0458932 , -0.01450805, -0.02789443,
        -0.02770494,  0.0213919 ,  0.02476374,  0.03355041, -0.00290108],
       [ 0.03116662, -0.00464839,  0.04717961,  0.00505186, -0.03915347,
         0.0466416 ,  0.01528276, -0.04908736, -0.02892902,  0.00599992],
       [-0.00455469, -0.02590811, -0.02185413,  0.02338172,  0.00481192,
        -0.02860378, -0.02556491,  0.016751  ,  0.01261909, -0.02747614],
       [-0.01447421,  0.00966493,  0.00402508, -0.02685664,  0.02896598,
         0.0061669 , -0.0273338 , -0.01832384, -0.04808456,  0.01997009],
       [ 0.04520038, -0.0310888 ,  0.0458932 , -0.01450805, -0.02789443,
        -0.02770494,  0.0213919 ,  0.02476374